### ISSUE TITLE
Selected element is not highlighted and properties is not displaying when private model is accessed from shared link

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1249]
When a private model is loaded from a link that contains the path to the element and a prefix for the side drawer property window to open, the following issues occur:
1. A message prompting the user to select an element is shown while the model is loading.
2. Once the model is loaded with the selected element, the side drawer property window is empty.
3. The selected element is not highlighted in the viewport.
4. The selected element is not highlighted in the tree view.

To view the properties and for the selection color to show up in the viewport and the tree, the side drawer needs to be closed and reopened.

Steps to Reproduce
1. Load a private model.
2. Select an element.
3. Open the properties drawer.
4. Open the share dialog.
5. Copy the link.
6. Paste the link into a new window.

Expected Behavior
- The model loads with the correct camera angle.
- The selected element is highlighted in the viewport.
- The selected element is highlighted in the tree.
- The element's properties are shown in the properties side drawer.

Observed Behavior
- The selected element is not highlighted in the viewport.
- The selected element is not highlighted in the tree.
- The properties side drawer is empty for the selected element.
- To view the properties and for the selection color to appear in the viewport and the tree, the side drawer needs to be closed and reopened.

**Comment by pablo-mayrgundter** [comment]
Console trace:

hook.js:608 General error: HttpError: Not Found - https://docs.github.com/rest/repos/contents#get-repository-content
    at index.js:100:21
    at async getGitHubResource (Http.js:50:22)
    at async getPathContents (Files.js:323:34)
    at async getGitHubPathContents (urls.js:160:48)
    at async dereferenceAndProxyDownloadContents (urls.js:144:14)
    at async load (Loader.js:79:50)
    at async loadModel (CadView.jsx:251:21)
    at async onViewer (CadView.jsx:183:21)
    at async CadView.jsx:544:11
